name: FGO Daily Login

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "30 03 * * *" #GMT+08: 11:30
    - cron: "30 13 * * *" #GMT+08: 21:30
    - cron: "30 17 * * *" #GMT+08: 1:30 (next day)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Install Requeriments
        run: pip install -r https://raw.githubusercontent.com/asahinobori/FgoDailyLogin/master/requirements.txt

      - name: Gettings files from Repo
        uses: actions/checkout@v2

      - name: Execute main script 1
        run: |
          python3 main.py
        env:
          userIds: ${{ secrets.GAME_USERIDS }}
          authKeys: ${{ secrets.GAME_AUTHKEYS }}
          secretKeys: ${{ secrets.GAME_SECRETKEYS }}
          UserAgent: ${{ secrets.GAME_USERAGENT }}
          fateRegion: ${{ secrets.GAME_REGION }}
          webhookDiscord: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Execute main script 2
        run: |
          python3 main02.py
        env:
          userIds: ${{ secrets.GAME_USERIDS }}
          authKeys: ${{ secrets.GAME_AUTHKEYS }}
          secretKeys: ${{ secrets.GAME_SECRETKEYS }}
          UserAgent: ${{ secrets.GAME_USERAGENT }}
          fateRegion: ${{ secrets.GAME_REGION }}
          webhookDiscord: ${{ secrets.DISCORD_WEBHOOK }}
